### ISSUE TITLE
[Safari] Can't find variable: AudioContext

### ISSUE THREAD

**Issue by ptrkrlsrd** [amaneureka/T-Rex#5]
Hey! When testing the website I'm getting an error in the console saying "Can't find variable: AudioContext".

I haven't tested it yet, but I think you can fix it by replacing _AudioContext_ with _webkitAudioContext_ when the client is using the desktop version of Safari.

**Comment by amaneureka** [comment]
Thanks!

I fixed it by adding following code block
```
var AudioContext = window.AudioContext          // Default
              || window.webkitAudioContext;  // Safari and old versions of Chrome
this.audioContext = new AudioContext();```
