### ISSUE TITLE
Explanation of mechanism

### ISSUE THREAD

**Issue by anantzoid** [amaneureka/T-Rex#8]
Would be good to have a brief explanation of how you're employing neural nets in deep reinforcement learning, how architectural changes in the network affect the learning performance (if you've worked that out) etc.

**Comment by amaneureka** [comment]
noted!
I make sure I update it as soon as possible with brief explanation.

PS. It could take several weeks because I have my finals going on in college

**Comment by jatin69** [comment]
Hey @amaneureka , still waiting on that explanation. lol.
It would be of great help if you could direct me to some resources helpful to get this.
Thanks,

**Comment by amaneureka** [comment]
ah. I am really sorry.

Explanation:

- I am using multilayer perceptron as architecture.
- Learning is based on reinforcement technique.

> ```brain.js``` line 57-87
>
> When tRex crash we calculate the reward point (or error)
> ```LastParams``` = {```DISTANCE```, ```WIDTH```, ```VELOCITY```}
> ```**DISTANCE**```: Distance from the approaching cactus
> ```**WIDTH**```: Width of the cactus
> ```**VELOCITY**```: Velocity of the game
>
>      if (tRexGameRunner.crashed)
>      {
>        // here I calculate the deltaFactor (distance / time)
>        var deltaFactor = ((LastParams[1]/LastParams[2]) * 10);// 10 is just adjusting factor
>
> Now that I calculated the time delta by which TRex has crashed in the cactus
> What was TRex doing before crash? Jumping or walking on ground
>
>        // jumpVelocity > 0 handles the case when TRex is in free fall
>        if (tRexGameRunner.tRex.jumpVelocity > 0 || tRexGameRunner.tRex.jumping)
>        {
>          perceptron.activate(LastParams);
>          // if TRex was jumping than it should't have jumped in the last move and stay DOWN
>          perceptron.propagate(learningRate, [0, 1]);// [UP, DOWN]
>
>          LastRealParams[0] = LastRealParams[0] + deltaFactor;
>          perceptron.activate(LastRealParams);
>          // But it should have jumped after the cactus has passed (if necessary)
>          perceptron.propagate(learningRate, [1, 0]); [UP, DOWN]
>        }
>        else
>        {
>          // if TRex was not jumping than it should have jumped at right moment i.e. +deltaFactor time
>          perceptron.activate(LastParams);
>          LastParams[0] = LastParams[0] + deltaFactor;
>          perceptron.activate(LastParams);
>          perceptron.propagate(learningRate, [1, 0]);
>        }
>      }

I hope this helps
